"""Add roles column to user table

Revision ID: 4b139f30f194
Revises: 1f92584bd938
Create Date: 2025-07-24 15:17:54.177470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4b139f30f194'
down_revision: Union[str, None] = '1f92584bd938'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usermodel', sa.Column('roles', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usermodel', 'roles')
    # ### end Alembic commands ###
