"""Se agrega tabla sueldos x empleado

Revision ID: 825bedc36192
Revises: 8b6b3f0403b8
Create Date: 2025-10-21 16:20:53.646625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '825bedc36192'
down_revision: Union[str, None] = '8b6b3f0403b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employeepricemodel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date_from', sa.Date(), nullable=False),
    sa.Column('cost_per_hour', sa.Float(), nullable=True),
    sa.Column('date_to', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['usermodel.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employeepricemodel_date_from'), 'employeepricemodel', ['date_from'], unique=False)
    op.create_index(op.f('ix_employeepricemodel_date_to'), 'employeepricemodel', ['date_to'], unique=False)
    op.create_index(op.f('ix_employeepricemodel_user_id'), 'employeepricemodel', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_employeepricemodel_user_id'), table_name='employeepricemodel')
    op.drop_index(op.f('ix_employeepricemodel_date_to'), table_name='employeepricemodel')
    op.drop_index(op.f('ix_employeepricemodel_date_from'), table_name='employeepricemodel')
    op.drop_table('employeepricemodel')
    # ### end Alembic commands ###
