"""add new table: notificacions bugfix

Revision ID: 8b6b3f0403b8
Revises: 0945dc610706
Create Date: 2025-07-30 16:51:53.596114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8b6b3f0403b8'
down_revision: Union[str, None] = '0945dc610706'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('timesheetlinenotificationmodel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timesheet_line_id', sa.Integer(), nullable=False),
    sa.Column('approver_id', sa.Integer(), nullable=False),
    sa.Column('receiver_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('ttl', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approver_id'], ['usermodel.id'], ),
    sa.ForeignKeyConstraint(['receiver_id'], ['usermodel.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_timesheetlinenotificationmodel_approver_id'), 'timesheetlinenotificationmodel', ['approver_id'], unique=False)
    op.create_index(op.f('ix_timesheetlinenotificationmodel_receiver_id'), 'timesheetlinenotificationmodel', ['receiver_id'], unique=False)
    op.create_index(op.f('ix_timesheetlinenotificationmodel_timesheet_line_id'), 'timesheetlinenotificationmodel', ['timesheet_line_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_timesheetlinenotificationmodel_timesheet_line_id'), table_name='timesheetlinenotificationmodel')
    op.drop_index(op.f('ix_timesheetlinenotificationmodel_receiver_id'), table_name='timesheetlinenotificationmodel')
    op.drop_index(op.f('ix_timesheetlinenotificationmodel_approver_id'), table_name='timesheetlinenotificationmodel')
    op.drop_table('timesheetlinenotificationmodel')
    # ### end Alembic commands ###
