"""tablas de logs para integracion humand-odoo

Revision ID: eb366ba8f21e
Revises: a43f954e2c06
Create Date: 2026-01-13 11:51:35.064120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'eb366ba8f21e'
down_revision: Union[str, None] = 'a43f954e2c06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('timeoff_sync_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('last_successful_run', sa.DateTime(), nullable=True),
    sa.Column('new_requests_synced', sa.Integer(), nullable=False),
    sa.Column('status_updates_synced', sa.Integer(), nullable=False),
    sa.Column('errors_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.String(length=2000), nullable=True),
    sa.Column('execution_time_seconds', sa.Float(), nullable=True),
    sa.Column('run_details', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('timeoff_sync_mapping',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('humand_request_id', sa.String(length=255), nullable=False),
    sa.Column('odoo_request_id', sa.Integer(), nullable=False),
    sa.Column('humand_user_email', sa.String(length=255), nullable=False),
    sa.Column('odoo_employee_id', sa.Integer(), nullable=False),
    sa.Column('sync_status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_sync_error', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('humand_request_id', name='uq_humand_request_id')
    )
    op.create_index('ix_humand_request_id', 'timeoff_sync_mapping', ['humand_request_id'], unique=False)
    op.create_index('ix_odoo_request_id', 'timeoff_sync_mapping', ['odoo_request_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_odoo_request_id', table_name='timeoff_sync_mapping')
    op.drop_index('ix_humand_request_id', table_name='timeoff_sync_mapping')
    op.drop_table('timeoff_sync_mapping')
    op.drop_table('timeoff_sync_log')
    # ### end Alembic commands ###
